services:
  uretim-planlama:
    build:
      context: .
      dockerfile: Dockerfile
    image: uretim-planlama
    container_name: uretim-planlama
    ports:
      - "5057:5057"
    restart: unless-stopped
    volumes:
      - uploads_data:/app/uploads

volumes:
  uploads_data:
