services:
  dokumhaneraporlama:
    build:
      context: .
      dockerfile: Dockerfile
    image: dokumhaneraporlama
    container_name: dokumhaneraporlama
    ports:
      - "5057:5057"
    restart: always
    volumes:
      - dokumhaneraporlama:/app/uploads

volumes:
  dokumhaneraporlama:
